### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by montagdude** [Dlackware/systemd#12]
Sorry if this is not the right place, as it's more of a question than an issue. Is there a documented safe way to uninstall systemd and revert to the standard Slackware init system? I can obviously reinstall all the original packages, but I fear I will be left with a broken system. This could be marked as a documentation issue, I suppose.

**Comment by belka-ew** [comment]
Questions are always welcome as well.

I don't think there is a non-destructive way to uninstall systemd. Maybe @bartgymnast can tell more.

**Comment by bartgymnast** [comment]
if not mistaken you can switch back to the old init,
however eudev will be missing,
you could try to use "slackpkg clean-system"
