### ISSUE TITLE
systemd-service-files installation error

### ISSUE THREAD

**Issue by belka-ew** [Dlackware/systemd#5]
systemd-service-files causes an error (not critical) on installation. It seems there is a problem in doinst.sh.

**Comment by bartgymnast** [comment]
This is now fixed.

Forgot to update it.

**Comment by belka-ew** [comment]
Created symlink from /etc/systemd/system/graphical.target.wants/update-gdk-pixbuf-loaders.service to /lib/systemd/system/update-gdk-pixbuf-loaders.service.
Failed to execute operation: No such file or directory
Removed symlink /etc/systemd/system/default.target.

**Comment by belka-ew** [comment]
Install the package after Gnome
