### ISSUE TITLE
apache doesn't start on boot

### ISSUE THREAD

**Issue by belka-ew** [Dlackware/systemd#6]
Missing service files for core slackware packages:
- [x] Apache
- [x] MariaDB
- [x] PHP-FPM
- [ ] CUPS
- [x] sendmail
- [ ] samba
- [x] ntpd
- [ ] netatalk

**Comment by belka-ew** [comment]
the same for mariadb (/etc/rc.d/rc.mysqld)

**Comment by bartgymnast** [comment]
we could rebuild them for systemd to actually use this. however primary focus is desktop software of gnome.

**Comment by bartgymnast** [comment]
or we can create minimalistic .service files that we supply thru the systemd-service-files.

**Comment by belka-ew** [comment]
systemd-service-files is the way to go imho. Rebuild this stuff only for this files is not worth it. You have to update them aswell every time slackware updates. Too much work.

**Comment by bartgymnast** [comment]
this should be left as a warning for now. and lets make a list of all standard services, and make unit files for it.
