### ISSUE TITLE
Upgrade to systemd 234

### ISSUE THREAD

**Issue by bogdanr** [Dlackware/systemd#9]
It would be nice to upgrade to systemd 234.

I think a bit of patching would be necessary to find all the libs it needs.

**Comment by belka-ew** [comment]
@bartgymnast, is it fixed now in [cad0b26](https://github.com/Dlackware/systemd/commit/00639d24c9cd250ee941f85dd9ed82eb11261b56)?

**Comment by bogdanr** [comment]
I confirm it is possible to compile systemd 234 on slackware-current after some updates done in slackware-current.

**Comment by belka-ew** [comment]
@bogdanr, thanks!
